### PR TITLE
Improve refreshToken and add Register process in instance option

### PR DESCRIPTION
**Pull request by TA2k**
I improved to refreshToken to make the adapter stable.
I also integrated a register process in the instance options to make it easier to get a working token.

I hope this helps top but the adapter in the latest repo

### CODE REVIEW

**Comment by firelook** [comment]
I put access to false, I have as usual
"

homeconnect.0 | 2019-04-03 12:08:27.445 | error | Error getting homeapplianceJSON with Token. Fehlercode: 401,The access token expired
-- | -- | -- | --


"
but it doesn't give me the next step to validate a new token ?

**Comment by TA2k** [comment]
I changed the option to reset to the instance options. Check "Zugriff zurücksetzen" and then on speichern und schließen to reset the token

**Comment by firelook** [comment]
I have only
`

 
--
access | access | state | indicator |   |   |   | editdeletebuild
authUriComplete | AuthorizationURI | state | indicator |   |   |   | editdeletebuild
devCode | DeviceCode | state | indicator |   |   |   | editdeletebuild
eventStreamJSON | Eventstream_JSON | state | indicator |   |   |   | editdeletebuild
expires | Token expires in sec | state | indicator |   |   |   | editdeletebuild
homeappliancesJSON | Homeappliances_JSON | state | indicator |   |   |   | editdeletebuild
pollInterval | Poll-Interval in sec. | state | indicator |   |   |   | editdeletebuild
refreshToken | Refresh-Token | state | indicator |   |   |   | editdeletebuild
token | Access-Token | state | indicator |   |   |   | editdeletebuild
 

`

**Comment by TA2k** [comment]
image
image

**Comment by firelook** [comment]
image

**Comment by firelook** [comment]
image

**Comment by TA2k** [comment]
in adapter which version is installed?

**Comment by TA2k** [comment]
Try to switch in Expert Mode in Adapter and press the up arrow for an adapter upload

**Comment by firelook** [comment]
image
this is in expert

**Comment by TA2k** [comment]
Adapter not instance

**Comment by firelook** [comment]
image

**Comment by TA2k** [comment]
ok press on the up arrow to reupload

**Comment by firelook** [comment]
done no change

**Comment by TA2k** [comment]
try to reinstall via github url. close browser. clear browser cache.

**Comment by firelook** [comment]
I reboot and now I see something in german  
image
I have to do some google translate

**Comment by firelook** [comment]
I put the client id, throught the log I see the request to authorize the id so now let's wait


thanks !!!!!!

**Comment by firelook** [comment]
seems working but I have a lot of errors in my log
`

fromCaughthomeconnect.0host.Obelix | Time | debugsillyinfowarnerror |  
-- | -- | -- | --


`

**Comment by TA2k** [comment]
504 means home connect is not reachable this happens often in the night maybe updates

**Pull request merged**
